//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8762
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoDrawingCollector.csproj.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50")]
        public global::System.Drawing.Point MessageLocation {
            get {
                return ((global::System.Drawing.Point)(this["MessageLocation"]));
            }
            set {
                this["MessageLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 200")]
        public global::System.Drawing.Size MessageSize {
            get {
                return ((global::System.Drawing.Size)(this["MessageSize"]));
            }
            set {
                this["MessageSize"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>B2-01-6F-32-BD-A0-D4-35-11-4D-40-09-16-58-0B-2F</string>
  <string>A5-E1-C2-0B-16-EB-35-E9-62-D3-1D-18-94-F0-81-80</string>
  <string>C6-D1-82-65-2B-53-7C-4A-D6-74-BF-33-69-75-A1-3E</string>
  <string>7D-37-E7-57-82-09-28-71-D3-0B-94-7D-AC-44-D2-0F</string>
  <string>70-02-2B-39-04-EA-3A-5E-9D-24-CD-E8-3B-36-F3-B7</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TableHashes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TableHashes"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string TargetPath {
            get {
                return ((string)(this["TargetPath"]));
            }
            set {
                this["TargetPath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Driver={SQL Server};SERVER=AMSTORE-SQL-05;DATABASE=ENGINEERING")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-PACKET")]
        public string Suffix {
            get {
                return ((string)(this["Suffix"]));
            }
            set {
                this["Suffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1175, 20")]
        public global::System.Drawing.Point PageStampLoc {
            get {
                return ((global::System.Drawing.Point)(this["PageStampLoc"]));
            }
            set {
                this["PageStampLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int PageStampSize {
            get {
                return ((int)(this["PageStampSize"]));
            }
            set {
                this["PageStampSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1154, 20, 47, 16")]
        public global::System.Drawing.Rectangle PageStampWhiteoutRectangle {
            get {
                return ((global::System.Drawing.Rectangle)(this["PageStampWhiteoutRectangle"]));
            }
            set {
                this["PageStampWhiteoutRectangle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoDeletePreMergedPDFs {
            get {
                return ((bool)(this["AutoDeletePreMergedPDFs"]));
            }
            set {
                this["AutoDeletePreMergedPDFs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Recurse {
            get {
                return ((bool)(this["Recurse"]));
            }
            set {
                this["Recurse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720, 20, 47, 16")]
        public global::System.Drawing.Rectangle PageStampWhiteoutRectangleA4 {
            get {
                return ((global::System.Drawing.Rectangle)(this["PageStampWhiteoutRectangleA4"]));
            }
            set {
                this["PageStampWhiteoutRectangleA4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("743, 20")]
        public global::System.Drawing.Point PageStampLocA4 {
            get {
                return ((global::System.Drawing.Point)(this["PageStampLocA4"]));
            }
            set {
                this["PageStampLocA4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int CompressionLevel {
            get {
                return ((int)(this["CompressionLevel"]));
            }
            set {
                this["CompressionLevel"] = value;
            }
        }
    }
}
